# 1. Configuración de Build (Construcción)
# Le dice a Netlify qué comando correr y qué carpeta publicar
[build]
  command = "npx expo export --platform web"
  publish = "dist"

# 2. Configuración de Redirección (¡ESTO ARREGLA EL 404!)
# Le dice a Netlify que si no encuentra una ruta (/*),
# debe enviar al index.html para que Expo Router se encargue.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200